### ISSUE TITLE
array out of bounds exception

### ISSUE THREAD

**Issue by philsmart** [philsmart/raptor-server#5]
Could not enrich event [227821657]

uk.ac.cardiff.raptor.server.enrich.EventAttributeEnricherException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at uk.ac.cardiff.raptor.server.enrich.LdapEventAttributeEnricher.enrich(LdapEventAttributeEnricher.java:94) ~[classes!/:0.1.0]
	at uk.ac.cardiff.raptor.server.enrich.EventEnricherService.enrich(EventEnricherService.java:52) ~[classes!/:0.1.0]
	at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:113) [spring-expression-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:102) [spring-expression-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49) [spring-expression-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347) [spring-expression-4.3

**Comment by philsmart** [comment]
Can not see where this is being generated. Will push back

**Comment by philsmart** [comment]
This will help.

Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[na:1.8.0_131]
	at java.util.LinkedList.get(LinkedList.java:476) ~[na:1.8.0_131]
	at uk.ac.cardiff.raptor.server.enrich.LdapEventAttributeEnricher.enrich(LdapEventAttributeEnricher.java:89) ~[classes!/:0.2.0]
